[en-us]
  languageName = "English"
  contentDir = "content/en-us"
  weight = 10
  [en-us.params]
    languageISO = "en-us"

[zh-cn]
  languageName = "中文"
  contentDir = "content/zh-cn"
  weight = 15
  [zh-cn.params]
    languageISO = "zh-cn"

[fr-fr]
  languageName = "français"
  contentDir = "content/fr-fr"
  weight = 20
  [fr-fr.params]
    languageISO = "fr-fr"
